name: test-ci
# base64 -i PROVISIONING_PROFILE.mobileprovision | pbcopy
on:
  # watch:
  #   types: started
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main


jobs:
  
  e1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test1"
      - run: echo "test2"
      - run: echo "::add-mask::${{ secrets.FEISHU_WEBHOOK_URL }}" | base64 --decode > lib/url_base64.txt

      - name: Output lib/url_base64.txt file to log
        run: cat lib/url_base64.txt   
  e2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test3"
      - run: echo "test4"  
      
  notify:
    needs: [e1, e2]
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Feishu
        if: always()
        run: |
          curl -X POST "$FEISHU_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d '{
            "msg_type": "text",
            "content": {
              "text": "CI/CD Job Status:\nAndroid Job: ${{ needs.android-deploy.result }} \niOS Job: ${{ needs.ios-deploy.result }}\nUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCommit: ${{ github.sha }}"
            }
          }'
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
