name: test-ci
# base64 -i PROVISIONING_PROFILE.mobileprovision | pbcopy
on:
  # watch:
  #   types: started
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

env:
  METHOD: "release-testing"
  TEAM_ID: "5NGD3B3V37"
  SIGNING_CERTIFICATE: "Apple Distribution: Shenzhen Snapmaker Technologies Co., Ltd. (5NGD3B3V37)"
  PROVISIONGPROFILENAME: "snapmakerAppAdhoc"
  BUILD_ID: "com.snapmaker.lavaapp"
  
jobs:
  
  e1:
    runs-on: ubuntu-latest
    steps:
    # 检出代码
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "$BUILD_ID"
      - run: echo "::add-mask::$BUILD_ID"

      - run: echo "::add-mask::${{ secrets.FEISHU_WEBHOOK_URL }}"
      - run: echo "${{ secrets.FEISHU_WEBHOOK_URL }}" | base64 --decode > lib/url_base64.txt
      
      - name: Output lib/url_base64.txt file to log
        run: cat lib/url_base64.txt   

    
      - name: Decode and save Android keystore
        env:
          ANDROID_ENCODED_KEYSTORE: ${{ secrets.FEISHU_WEBHOOK_URL }}
        run: |
          # Decode and write the keystore to a file
          echo "$ANDROID_ENCODED_KEYSTORE" | base64 --decode > lib/url_base64.jks

      #"::add-mask::"
  e2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test3"
      - run: echo "test4"  
      
  notify:
    needs: [e1, e2]
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Feishu
        if: always()
        run: |
          curl -X POST "$FEISHU_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d '{
            "msg_type": "text",
            "content": {
              "text": "CI/CD Job Status:\nAndroid Job: ${{ needs.android-deploy.result }} \niOS Job: ${{ needs.ios-deploy.result }}\nUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCommit: ${{ github.sha }}"
            }
          }'
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
