name: CI/CD
# base64 -i PROVISIONING_PROFILE.mobileprovision | pbcopy
on:
  # watch:
  #   types: started
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:       
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Feishu
        if: always()
        run: |
          COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | jq -R .)
          echo $COMMIT_MESSAGE
          curl -X POST "$FEISHU_WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d '{
            "msg_type": "text",
            "content": {
              "text": "CI/CD Job Status:\nAndroid Job: ${{ needs.android-deploy.result }} \niOS Job: ${{ needs.ios-deploy.result }}\nUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCommit: ${{ github.sha }}\nCommit Message: $COMMIT_MESSAGE\nAuthor: ${{ github.actor }}\nPR Number: ${{ github.event.pull_request.number }}\nPR Title: ${{ github.event.pull_request.title }}\nPR Description: ${{ github.event.pull_request.body }}\nPR Commit SHA: ${{ github.event.pull_request.head.sha }}"
            }
          }'
        env:
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
